<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net462</TargetFramework>
    <RootNamespace>TestMod</RootNamespace>
    <AssemblyName>TestMod</AssemblyName>
    <LangVersion>latest</LangVersion>
    <Deterministic>true</Deterministic>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <DebugType>full</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>bin\Debug</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DefineConstants>TRACE</DefineConstants>
    <DebugType>full</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>bin\Release\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="ColorChanger.cs" />
    <Compile Include="ConsoleCommands\AdminCheckCommand.cs" />
    <Compile Include="ConsoleCommands\EchoCommand.cs" />
    <Compile Include="ConsoleCommands\RemoveCategoryTabCommand.cs" />
    <Compile Include="ConsoleCommands\ResetCartographyCommand.cs" />
    <Compile Include="ConsoleCommands\CreateCategoryTabCommand.cs" />
    <Compile Include="ConsoleCommands\ListPlayersCommand.cs" />
    <Compile Include="ConsoleCommands\SkinColorCommand.cs" />
    <Compile Include="ConsoleCommands\BetterSpawnCommand.cs" />
    <Compile Include="ConsoleCommands\PrintItemsCommand.cs" />
    <Compile Include="ConsoleCommands\TpCommand.cs" />
    <Compile Include="GradientChanger.cs" />
    <Compile Include="PatchInit\TestPatchInitialization.cs" />
    <Compile Include="Properties\IgnoreAccessModifiers.cs" />
    <Compile Include="TestModDungeon.cs" />
    <Compile Include="TestRPCs.cs" />
    <Compile Include="TestReferences.cs" />
    <Compile Include="TestMod.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
    <Compile Include="TestMod2.cs" />
    <Compile Include="TestMapDrawing.cs" />
    <Compile Include="TestUndo.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="app.config" />
    <EmbeddedResource Include="AssetsEmbedded\steel" />
    <EmbeddedResource Include="AssetsEmbedded\kitbash" />
    <EmbeddedResource Include="AssetsEmbedded\cheatsword" />
    <EmbeddedResource Include="AssetsEmbedded\custom_locations" />
    <EmbeddedResource Include="AssetsEmbedded\creatures" />
    <EmbeddedResource Include="AssetsEmbedded\dolmenexample" />
    <None Include="Assets\jotunnlibtest" />
    <EmbeddedResource Include="AssetsEmbedded\capeironbackpack" />
    <None Include="Assets\recipes.json" />
    <None Include="Assets\skills.json" />
    <None Include="Assets\testblueprints" />
    <None Include="Assets\Translations\English\backpack.english.json" />
    <None Include="Assets\Translations\English\translations.json" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="AssetsEmbedded\pieces" />
    <EmbeddedResource Include="AssetsEmbedded\clutterbundle" />
    <Content Include="Assets\test_tex.jpg" />
    <Content Include="Assets\reee.png" />
    <Content Include="Assets\test_var1.png" />
    <Content Include="Assets\test_var2.png" />
    <Content Include="Assets\test_var4.png" />
    <Content Include="Assets\test_varpaint.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JotunnLib\JotunnLib.csproj" />
  </ItemGroup>

  <Target Name="CopyToPluginFolder" AfterTargets="Build" Condition="'$(OS)' == 'Windows_NT'">
    <Exec Command="powershell.exe -ExecutionPolicy RemoteSigned -File &quot;$(SolutionDir)publish.ps1&quot; -Target &quot;$(ConfigurationName)&quot; -TargetPath &quot;$(TargetDir.TrimEnd('\'))&quot; -TargetAssembly &quot;$(TargetFileName)&quot; -ValheimPath &quot;$(VALHEIM_INSTALL.TrimEnd('\'))&quot; -DeployPath &quot;$(MOD_DEPLOYPATH.TrimEnd('\'))&quot; -ProjectPath &quot;$(ProjectDir.TrimEnd('\'))&quot;" />
    <Exec Command="xcopy &quot;$(ProjectDir)Assets&quot; &quot;$(MOD_DEPLOYPATH)\TestMod\Assets\&quot; /S /Y" />
  </Target>

  <Import Project="$(SolutionDir)JotunnLib\BuildProps\Paths.props" />
  <Import Project="$(SolutionDir)JotunnLib\BuildProps\JotunnLibRefsCorlib.props" />
</Project>
