@startuml
'' flow
!pragma teoz true
hide footbox

participant Valheim
participant BepInEx

box JotunnMods
    collections JotunnMod
end box

box Jotunn
    participant LocalizationManager
    participant CreatureManager
    participant PrefabManager
    participant PieceManager
    participant ItemManager
    participant ZoneManager
    participant GUIManager
    participant MinimapManager
    participant SynchronizationManager
end box

group For each mod
    ?->JotunnMod **: Loaded by\nBepInEx
    JotunnMod -> JotunnMod ++ #lightgreen: Awake
end group

== Main Menu Scene ==

Valheim -> Valheim++: ClutterSystem.Awake
    hnote over ZoneManager: OnVanillaClutterAvailable
    hnote over ZoneManager: OnClutterRegistered
deactivate Valheim

Valheim -> Valheim++: FejdStartup.SetupGui
    hnote over GUIManager: OnCustomGUIAvailable
    hnote over LocalizationManager: OnLocalizationAdded
deactivate Valheim

Valheim -> Valheim++: ObjectDB.CopyOtherDB
    hnote over CreatureManager: OnVanillaCreaturesAvailable
    hnote over PrefabManager: OnVanillaPrefabsAvailable
    hnote over ItemManager: OnItemsRegisteredFejd
deactivate Valheim

note over Valheim #lightblue: Main menu interactable

== Loading Scene ==
== Game Scene  ==

Valheim -> Valheim++: ZNetScene.Awake
    hnote over CreatureManager: OnCreaturesRegistered
    hnote over PrefabManager: OnPrefabsRegistered
deactivate Valheim

Valheim -> Valheim++: ObjectDB.Awake
    hnote over ItemManager: OnItemsRegistered
    hnote over PieceManager: OnPiecesRegistered
deactivate Valheim

Valheim -> Valheim++: ClutterSystem.Awake
    hnote over ZoneManager: OnVanillaClutterAvailable
    hnote over ZoneManager: OnClutterRegistered
deactivate Valheim

Valheim -> Valheim++: Game.Start
    hnote over GUIManager: OnCustomGUIAvailable
deactivate Valheim

Valheim -> Valheim++: ZoneSystem.SetupLocations
    hnote over ZoneManager: OnVanillaLocationsAvailable
    hnote over ZoneManager: OnLocationsRegistered
    hnote over ZoneManager: OnVanillaVegetationAvailable
    hnote over ZoneManager: OnVegetationRegistered
deactivate Valheim

Valheim -> Valheim++: Minimap.Start
    hnote over MinimapManager: OnVanillaMapAvailable
deactivate Valheim

Valheim -> Valheim++: Minimap.LoadMapData
    hnote over MinimapManager: OnVanillaMapDataLoaded
deactivate Valheim

group client (only if connecting to a server)
Valheim -> Valheim++: ZRoutedRpc.HandleRoutedRPC
    hnote over SynchronizationManager: OnAdminStatusChanged
    hnote over SynchronizationManager: OnSyncingConfiguration
    hnote over SynchronizationManager: OnConfigurationSynchronized
deactivate Valheim
end group

note over Valheim #lightblue: Game interactable

@enduml
