using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using UnityEngine;
using UnityEngine.SceneManagement;
using JotunnLib.Managers;
using JotunnLib.Utils;

namespace JotunnDoc.Docs
{
    public class InputDoc : Doc
    {
        public InputDoc() : base("JotunnDoc/Docs/conceptual/input/input-list.md")
        {
            SceneManager.sceneLoaded += docInputs;
        }

        public void docInputs(Scene scene, LoadSceneMode mode)
        {
            if (Generated)
            {
                return;
            }

            if (scene.name != "main")
            {
                return;
            }

            Debug.Log("Documenting inputs");

            AddHeader(1, "Input list");
            AddText("All of the inputs currently in the game, and their default values.");
            AddText("This file is automatically generated from Valheim using the JotunnDoc mod found on our GitHub.");
            AddTableHeader("Name", "Keycode", "Axis", "Gamepad");

            var buttons = ReflectionUtils.GetPrivateField<Dictionary<string, ZInput.ButtonDef>>(ZInput.instance, "m_buttons");

            foreach (var pair in buttons)
            {
                ZInput.ButtonDef button = pair.Value;
                AddTableRow(pair.Key, button.m_key.ToString(), button.m_axis, button.m_gamepad.ToString());
            }

            Save();
        }
    }
}
