using System.Collections.Generic;
using UnityEngine.SceneManagement;

namespace JotunnDoc.Docs
{
    class LanguageDoc : Doc
    {
        private List<Doc> subDocs = new List<Doc>();

        public LanguageDoc() : base("localization/language-list.md")
        {
            SceneManager.sceneLoaded += DocLanguages;
        }

        private void DocLanguages(Scene scene, LoadSceneMode mode)
        {
            if (Generated)
            {
                return;
            }

            Jotunn.Logger.LogInfo("Documenting languages");

            AddHeader(1, "Language list");
            AddText("All of the languages currently in the game, with links to detailed translations for each.");
            AddText($"This file is automatically generated from Valheim {Version.GetVersionString(true)} using the JotunnDoc mod found on our GitHub.");

            AddTableHeader("Folder Name", "Localized Name", "Translations");

            var userLanguage = Localization.instance.GetSelectedLanguage();

            foreach (var languageKey in Localization.instance.m_languages)
            {
                var localizedName = Localization.instance.Localize("$language_" + languageKey.ToLower());
                var translationsLink = $"[Translations](translations/{languageKey}.md)";
                AddTableRow(languageKey, localizedName, translationsLink);
                subDocs.Add(new TranslationListDoc(languageKey));
            }

            Localization.instance.SetupLanguage(userLanguage);

            Save();
        }

        class TranslationListDoc : Doc
        {
            public TranslationListDoc(string languageKey) : base($"localization/translations/{languageKey}.md")
            {
                if (Generated)
                {
                    return;
                }

                Localization.instance.SetupLanguage(languageKey);

                Jotunn.Logger.LogInfo($"Documenting {languageKey} translations");

                AddHeader(1, $"{languageKey} translations list");
                AddText($"All of the translation keys and {languageKey} text currently in the game.");
                AddText($"This file is automatically generated from Valheim {Version.GetVersionString(true)} using the JotunnDoc mod found on our GitHub.");

                AddTableHeader("Key", $"{languageKey} Text");

                var keys = new List<string>(Localization.instance.m_translations.Keys);
                keys.Sort();

                foreach (var key in keys)
                {
                    var text = Localization.instance.Localize("$" + key);
                    AddTableRow("$" + key, text.Replace("\n", "<br/>"));
                }

                Save();
            }
        }
    }
}
