using System;
using System.Collections.Generic;
using System.Linq;
using Jotunn.Managers;
using SoftReferenceableAssets;
using UnityEngine;

namespace JotunnDoc.Docs
{
    public class MeshDoc : Doc
    {
        public MeshDoc() : base("prefabs/mesh-list.md")
        {
            PrefabManager.OnVanillaPrefabsAvailable += DocMeshes;
        }

        void DocMeshes()
        {
            if (Generated)
            {
                return;
            }

            Jotunn.Logger.LogInfo("Documenting meshes");

            AddHeader(1, "Mesh list");
            AddText("All the meshes currently in the game.");
            AddText($"This file is automatically generated from Valheim {Version.GetVersionString()} using the JotunnDoc mod found on our GitHub.");

            List<KeyValuePair<string, AssetID>> allMeshes = AssetManager.Instance.MapNameToAssetID[typeof(Mesh)]
                .Where(pair => pair.Value.IsValid)
                .ToList();

            int splitCount = 2;
            int chunkSize = (int)Math.Ceiling((double)allMeshes.Count / splitCount);

            for (int i = 0; i < splitCount; i++)
            {
                var chunk = allMeshes.Skip(i * chunkSize).Take(chunkSize);

                AddTableHeader("SoftReference Name", "Asset ID", "Internal Object Name");

                foreach (var pair in chunk)
                {
                    AddMeshTableRow(pair.Key, pair.Value);
                }
            }

            Save();
        }

        private void AddMeshTableRow(string softReferenceName, AssetID assetID)
        {
            SoftReference<GameObject> asset = new SoftReference<GameObject>(assetID);
            asset.Load();

            if (!PrefabManager.TryFindAssetInSelfOrChildComponents(asset.Asset, typeof(Mesh), out UnityEngine.Object meshAsset))
            {
                return;
            }

            AddTableRow(softReferenceName, assetID.ToString(), meshAsset.name);
        }
    }
}
