using Jotunn.Managers;
using SoftReferenceableAssets;
using UnityEngine;
using Object = UnityEngine.Object;

namespace JotunnDoc.Docs
{
    public class MeshDoc : Doc
    {
        public MeshDoc() : base("prefabs/mesh-list.md")
        {
            PrefabManager.OnVanillaPrefabsAvailable += DocMeshes;
        }

        void DocMeshes()
        {
            if (Generated)
            {
                return;
            }

            Jotunn.Logger.LogInfo("Documenting meshes");

            AddHeader(1, "Mesh list");
            AddText("All the meshes currently in the game.");
            AddText("Use the SoftReference system to load the meshes, the internal object name is only for reference.");
            AddText($"This file is automatically generated from Valheim {Version.GetVersionString(true)} using the JotunnDoc mod found on our GitHub.");

            AddTableHeader("SoftReference Name", "Asset ID", "Internal Object Name");

            foreach (var pair in AssetManager.Instance.MapNameToAssetID[typeof(Mesh)])
            {
                if (!pair.Value.IsValid)
                {
                    continue;
                }

                var softReferenceName = pair.Key;
                var assetID = pair.Value;
                SoftReference<GameObject> asset = new SoftReference<GameObject>(assetID);
                asset.Load();

                if (!PrefabManager.TryFindAssetInSelfOrChildComponents(asset.Asset, typeof(Mesh), out Object meshAsset))
                {
                    continue;
                }

                AddTableRow(softReferenceName, assetID.ToString(), meshAsset.name);
            }
        }
    }
}
