using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Jotunn.Managers;
using Jotunn.Utils;
using UnityEngine;

namespace JotunnDoc.Docs
{
    public class PieceDoc : Doc
    {
        public PieceDoc() : base("pieces/piece-list.md")
        {
            PieceManager.OnPiecesRegistered += DocPieces;
        }

        public void DocPieces()
        {
            if (Generated)
            {
                return;
            }

            Jotunn.Logger.LogInfo("Documenting pieces");

            AddHeader(1, "Piece list");
            AddText("All of the pieces currently in the game.");
            AddText($"This file is automatically generated from Valheim {Version.GetVersionString(true)} using the JotunnDoc mod found on our GitHub.");

            var imageDirectory = Path.Combine(DocumentationDirConfig.Value, "images/pieces");
            Directory.CreateDirectory(imageDirectory);

            var pieceTables = ReflectionHelper.GetPrivateField<Dictionary<string, PieceTable>>(PieceManager.Instance, "PieceTableMap");

            foreach (var pair in pieceTables)
            {
                AddHeader(2, pair.Key);
                AddTableHeader("Piece", "Token", "Name", "Description", "Resources required");

                foreach (GameObject obj in pair.Value.m_pieces.Where(x => PieceManager.Instance.GetPiece(x.name) == null))
                {
                    Piece piece = obj.GetComponent<Piece>();

                    if (piece == null)
                    {
                        continue;
                    }

                    bool hasSprite = RequestSprite(Path.Combine(imageDirectory, $"{obj.name}.png"), obj, RenderManager.IsometricRotation);

                    string resources = "<ul>";

                    foreach (Piece.Requirement req in piece.m_resources)
                    {
                        resources += $"<li>{req.m_amount} {JotunnDoc.Localize(req?.m_resItem?.m_itemData?.m_shared?.m_name)}</li>";
                    }

                    resources += "</ul>";

                    AddTableRow(
                        GetNameBox(obj.name, hasSprite),
                        piece.m_name,
                        JotunnDoc.Localize(piece.m_name),
                        JotunnDoc.Localize(piece.m_description),
                        resources);
                }
            }

            Save();
        }
        private static string GetNameBox(string name, bool hasSprite)
        {
            StringBuilder sb = new StringBuilder(name);
            if (hasSprite)
            {
                sb.Append($"<br><img src=\"../../images/pieces/{name}.png\">");
            }
            return sb.ToString();
        }
    }
}
