using Jotunn.Managers;
using UnityEngine;

namespace JotunnDoc.Docs
{
    public class PrefabDoc : Doc
    {
        public PrefabDoc() : base("prefabs/prefab-list.md")
        {
            PrefabManager.OnPrefabsRegistered += DocPrefabs;
        }

        private void DocPrefabs()
        {
            if (Generated)
            {
                return;
            }

            Jotunn.Logger.LogInfo("Documenting prefabs");

            AddHeader(1, "Prefab list");
            AddText("All of the prefabs currently in the game.");
            AddText("This file is automatically generated from Valheim using the JotunnDoc mod found on our GitHub.");
            AddTableHeader("Name", "Components");

            foreach (GameObject obj in ZNetScene.instance.m_prefabs)
            {
                string components = "<ul>";

                foreach (Component comp in obj.GetComponents<Component>())
                {
                    components += "<li>" + comp.GetType().Name + "</li>";
                }

                components += "</ul>";

                AddTableRow(obj.name, components);
            }

            Save();
        }
    }
}
