using System;
using System.Collections.Generic;
using System.Linq;
using Jotunn.Entities;
using Jotunn.Managers;
using JotunnDoc.Patches;
using UnityEngine;

namespace JotunnDoc.Docs
{
    public class PrefabDoc : Doc
    {
        public PrefabDoc() : base("prefabs/prefab-list.md")
        {
            GameEvents.OnPlayerSpawned += DocPrefabs;
        }

        private void DocPrefabs(Player self)
        {
            if (Generated)
            {
                return;
            }

            Jotunn.Logger.LogInfo("Documenting prefabs");

            AddHeader(1, "Prefab list");
            AddText("All of the prefabs currently in the game (ZNetScene and ZoneManager).");
            AddText($"This file is automatically generated from Valheim {Version.GetVersionString()} using the JotunnDoc mod found on our GitHub.");

            foreach (var location in ZoneSystem.instance.m_locations)
            {
                if (location.m_prefab.IsValid)
                {
                    location.m_prefab.Load();
                }
            }

            List<GameObject> allPrefabs = new List<GameObject>();
            allPrefabs.AddRange(ZNetScene.instance.m_nonNetViewPrefabs);
            allPrefabs.AddRange(ZNetScene.instance.m_prefabs);
            allPrefabs.AddRange(ZoneSystem.instance.m_locations.Where(x => x.m_prefab.IsValid).Select(x => x.m_prefab.Asset));

            allPrefabs.RemoveAll(x => CustomPrefab.IsCustomPrefab(x.name));
            allPrefabs = allPrefabs.OrderBy(x => x.name).ToList();

            var prefabsAM = allPrefabs.Where(p => p.name.Length >= 1 && p.name.ToLower()[0] < 'm');
            var prefabsMZ = allPrefabs.Where(p => p.name.Length >= 1 && p.name.ToLower()[0] >= 'm');

            AddTableHeader("Name", "AssetID", "Token", "English Name", "Components", "Components in Children");

            foreach (GameObject obj in prefabsAM)
            {
                AddPrefabTableRow(obj);
            }

            AddTableHeader("Name", "AssetID", "Token", "English Name", "Components", "Components in Children");

            foreach (GameObject obj in prefabsMZ)
            {
                AddPrefabTableRow(obj);
            }

            Save();
        }

        private void AddPrefabTableRow(GameObject prefab)
        {
            string token = GetTokenOfPrefab(prefab);
            string englishName = string.IsNullOrEmpty(token) ? string.Empty : JotunnDoc.Localize(token);

            AddTableRow(
                prefab.name,
                AssetManager.Instance.GetAssetID<GameObject>(prefab.name).ToString(),
                token,
                englishName,
                GenerateComponentList(prefab.GetComponents<Component>()),
                GenerateChildComponentsList(prefab)
            );
        }

        private string GenerateComponentList(IEnumerable<Component> components)
        {
            string result = "<ul>";

            foreach (Type comp in components.Select(c => c.GetType()).Where(c => c != typeof(Transform)).Distinct())
            {
                result += $"<li>{comp.Name}</li>";
            }

            result += "</ul>";
            return result;
        }

        private string GenerateChildComponentsList(GameObject prefab)
        {
            List<Component> components = new List<Component>();

            foreach (Transform child in prefab.transform)
            {
                components.AddRange(child.GetComponentsInChildren<Component>(true));
            }

            return GenerateComponentList(components);
        }

        private string GetTokenOfPrefab(GameObject prefab)
        {
            if (prefab.TryGetComponent(out Piece piece) && !string.IsNullOrEmpty(piece.m_name)) return piece.m_name;
            if (prefab.TryGetComponent(out ItemDrop itemDrop) && itemDrop?.m_itemData?.m_shared != null && !string.IsNullOrEmpty(itemDrop.m_itemData.m_shared.m_name)) return itemDrop.m_itemData.m_shared.m_name;
            if (prefab.TryGetComponent(out Character character) && !string.IsNullOrEmpty(character.m_name)) return character.m_name;
            if (prefab.TryGetComponent(out Trader trader) && !string.IsNullOrEmpty(trader.m_name)) return trader.m_name;
            if (prefab.TryGetComponent(out HoverText hoverText) && !string.IsNullOrEmpty(hoverText.m_text)) return hoverText.m_text;
            if (prefab.TryGetComponent(out Aoe aoe) && !string.IsNullOrEmpty(aoe.m_name)) return aoe.m_name;
            if (prefab.TryGetComponent(out Hoverable hoverable))
            {
                try
                {
                    return hoverable.GetHoverName();
                }
                catch (Exception e)
                {
                    // ignore
                }
            }
            return string.Empty;
        }
    }
}
