using System.Linq;
using Jotunn.Managers;

namespace JotunnDoc.Docs
{
    public class RecipeDoc : Doc
    {
        public RecipeDoc() : base("objects/recipe-list.md")
        {
            ItemManager.OnItemsRegistered += DocRecipes;
        }

        private void DocRecipes()
        {
            if (Generated)
            {
                return;
            }

            Jotunn.Logger.LogInfo("Documenting recipes");

            AddHeader(1, "Recipe list");
            AddText("All of the recipes currently in the game, with English localizations applied");
            AddText("This file is automatically generated from Valheim using the JotunnDoc mod found on our GitHub.");
            AddTableHeader("Name", "Item name", "Amount", "Resources required");

            foreach (Recipe recipe in ObjectDB.instance.m_recipes.Where(x => ItemManager.Instance.GetRecipe(x.name) == null))
            {
                if (recipe == null)
                {
                    continue;
                }

                string resources = "<ul>";

                foreach (Piece.Requirement req in recipe.m_resources)
                {
                    resources += "<li>" + req.m_amount + " " +
                        JotunnDoc.Localize(req?.m_resItem?.m_itemData?.m_shared?.m_name) + "</li>";
                }

                resources += "</ul>";

                AddTableRow(
                    recipe.name,
                    JotunnDoc.Localize(recipe?.m_item?.m_itemData?.m_shared?.m_name),
                    recipe.m_amount.ToString(),
                    resources);
            }

            Save();
        }
    }
}
