using System.Collections.Generic;
using System.Linq;
using Jotunn.Managers;

namespace JotunnDoc.Docs
{
    public class RecipeDoc : Doc
    {
        public RecipeDoc() : base("objects/recipe-list.md")
        {
            ItemManager.OnItemsRegistered += DocRecipes;
        }

        private void DocRecipes()
        {
            if (Generated)
            {
                return;
            }

            Jotunn.Logger.LogInfo("Documenting recipes");

            AddHeader(1, "Recipe list");
            AddText("All the recipes currently in the game, with English localizations applied.");
            AddText($"This file is automatically generated from Valheim {Version.GetVersionString()} using the JotunnDoc mod found on our GitHub.");
            AddTableHeader("Name", "AssetID", "Item name", "Amount", "Resources required");

            foreach (Recipe recipe in ObjectDB.instance.m_recipes.Where(x => ItemManager.Instance.GetRecipe(x.name) == null))
            {
                ItemDrop.ItemData.SharedData sharedData = recipe ? recipe.m_item?.m_itemData?.m_shared : null;

                if (!recipe)
                {
                    continue;
                }

                string resources = string.Empty;

                if (sharedData == null || sharedData.m_maxQuality <= 1)
                {
                    resources += MakeResourceList(recipe.m_resources, 0);
                }
                else
                {
                    for (int level = 0; level < sharedData.m_maxQuality; level++)
                    {
                        resources += $"Level {level + 1}:";
                        resources += MakeResourceList(recipe.m_resources, level);
                    }
                }

                AddTableRow(
                    recipe.name,
                    AssetManager.Instance.GetAssetID<Recipe>(recipe.name).ToString(),
                    JotunnDoc.Localize(recipe.m_item),
                    recipe.m_amount.ToString(),
                    resources
                );
            }

            Save();
        }

        private static string MakeResourceList(Piece.Requirement[] resources, int level)
        {
            List<string> result = new List<string>();

            foreach (Piece.Requirement req in resources)
            {
                if (req == null)
                {
                    continue;
                }

                if (level == 0 && req.m_amount > 0)
                {
                    result.Add($"{req.m_amount} {JotunnDoc.Localize(req.m_resItem)}");
                }

                if (level > 0 && req.m_amountPerLevel > 0)
                {
                    result.Add($"{req.m_amountPerLevel * level} {JotunnDoc.Localize(req.m_resItem)}");
                }
            }

            return JotunnDoc.MakeList(result);
        }
    }
}
