using UnityEngine;
using UnityEngine.SceneManagement;
using System.Linq;

namespace JotunnDoc.Docs
{
    public class SpriteDoc : Doc
    {
        public SpriteDoc() : base("gui/sprite-list.md")
        {
            SceneManager.sceneLoaded += DocSprites;
        }

        public void DocSprites(Scene scene, LoadSceneMode mode)
        {
            if (Generated)
            {
                return;
            }

            if (scene.name != "main")
            {
                return;
            }

            Jotunn.Logger.LogInfo("Documenting Sprites");

            AddHeader(1, "Sprite list");
            AddText("All of the Sprites currently in the game.");
            AddText($"This file is automatically generated from Valheim {Version.GetVersionString()} using the JotunnDoc mod found on our GitHub.");
            AddTableHeader("Name", "TextureAtlas", "Coords");

            var sprites = Resources.FindObjectsOfTypeAll<Sprite>().OrderBy(x => x.name);

            foreach (var sprite in sprites)
            {
                AddTableRow(sprite.name, sprite.texture.name, sprite.textureRect.ToString());
            }

            Save();
        }
    }
}
