using System.Collections.Generic;
using UnityEngine;
using Jotunn.Managers;

namespace JotunnDoc.Docs
{
    public class StatusEffectDoc : Doc
    {
        public StatusEffectDoc() : base("status-effects/status-effect-list.md")
        {
            ItemManager.OnItemsRegistered += DocStatusEffects;
        }

        private void DocStatusEffects()
        {
            if (Generated)
            {
                return;
            }

            Jotunn.Logger.LogInfo("Documenting status effects");

            AddHeader(1, "Status effect list");
            AddText("All of the status effects currently in the game, with English localizations applied");
            AddText("This file is automatically generated from Valheim using the JotunnDoc mod found on our GitHub.");
            AddTableHeader("Object", "Name", "Category");

            Dictionary<string, StatusEffect> statusEffects = new Dictionary<string, StatusEffect>();

            foreach (GameObject obj in ObjectDB.instance.m_items)
            {
                ItemDrop item = obj.GetComponent<ItemDrop>();
                ItemDrop.ItemData.SharedData shared = item.m_itemData.m_shared;

                if (shared.m_attackStatusEffect)
                {
                    statusEffects[shared.m_attackStatusEffect.name] = shared.m_attackStatusEffect;
                }

                if (shared.m_consumeStatusEffect)
                {
                    statusEffects[shared.m_consumeStatusEffect.name] = shared.m_consumeStatusEffect;
                }

                if (shared.m_equipStatusEffect)
                {
                    statusEffects[shared.m_equipStatusEffect.name] = shared.m_equipStatusEffect;
                }

                if (shared.m_setStatusEffect)
                {
                    statusEffects[shared.m_setStatusEffect.name] = shared.m_setStatusEffect;
                }
            }

            foreach (StatusEffect statusEffect in statusEffects.Values)
            {
                AddTableRow(
                    statusEffect.name,
                    JotunnDoc.Localize(statusEffect.m_name),
                    JotunnDoc.Localize(statusEffect.m_category));
            }

            Save();
        }
    }
}
