using Jotunn.Managers;

namespace JotunnDoc.Docs
{
    public class StatusEffectDoc : Doc
    {
        public StatusEffectDoc() : base("status-effects/status-effect-list.md")
        {
            ItemManager.OnItemsRegistered += DocStatusEffects;
        }

        private void DocStatusEffects()
        {
            if (Generated)
            {
                return;
            }

            Jotunn.Logger.LogInfo("Documenting status effects");

            AddHeader(1, "Status effect list");
            AddText("All of the status effects currently in the game, with English localizations applied.");
            AddText($"This file is automatically generated from Valheim {Version.GetVersionString(true)} using the JotunnDoc mod found on our GitHub.");
            AddTableHeader("Object", "AssetID", "English Name", "Category");

            foreach (StatusEffect statusEffect in ObjectDB.instance.m_StatusEffects)
            {
                AddTableRow(
                    statusEffect.name,
                    AssetManager.Instance.GetAssetID<StatusEffect>(statusEffect.name).ToString(),
                    JotunnDoc.Localize(statusEffect.m_name),
                    JotunnDoc.Localize(statusEffect.m_category));
            }

            Save();
        }
    }
}
